make: practica1_integers.c practica1_float.c practica1_double.c practica1_strings_length.c practica1_strings_content.c
	gcc practica1_integers.c -o p1_1
	gcc practica1_float.c -o p1_2
	gcc practica1_double.c -o p1_3
	gcc practica1_strings_length.c -o p1_4
	gcc practica1_strings_content.c -o p1_5
